// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Technexa.Data;

#nullable disable

namespace Technexa.Migrations
{
    [DbContext(typeof(DBContextApplication))]
    [Migration("20231224191855_CategorieMigrations")]
    partial class CategorieMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Technexa.Models.Categorie", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("Technexa.Models.Post", b =>
                {
                    b.Property<int>("idpost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idpost"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SrcYoutubeVedio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categorieDesignation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categorieid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("idpost");

                    b.HasIndex("categorieid");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Technexa.Models.Post", b =>
                {
                    b.HasOne("Technexa.Models.Categorie", "categorie")
                        .WithMany()
                        .HasForeignKey("categorieid");

                    b.Navigation("categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
